### ISSUE TITLE
Speed controls are not disabled when the warp drive is enabled.

### ISSUE THREAD

**Issue by ehharvey** [kstencell/CSCN72030-Sec1-Group1#22]
When the wrap drive is enabled, the user is still able to briefly modify the speed control. The level 'rubber bands' back to max value.

Given that the direction control is fully properly locked, it may be worth also locking speed controls.

This also seems like a straightforward fix, so @pankitthakkar or @tsparks9038 can tackle it if you'd like.

**Comment by kstencell** [comment]
Same idea as the other thread, I thought it would be a straight forward fix but apparently it's not.

If I toggle the isEnabled property of speedSlider before the program runs then it can't be interacted with (hooray), but when I try to change speedSlider.isEnabled = false for example when warp drive is on, you can still move the slider around which is weird.

If anyone has time to fiddle with it, then by all means! Good that you made a thread about that because I should have done that when I was working on it yesterday.

**Comment by ehharvey** [comment]
Implemented. Await PR
